<?php

return [
    'invoice_items' => [
        [
            'product_code' => 'ABC-123-X',
            'name' => 'Lorem Product 1',
            'qty' => 5,
            'unit_price' => 1320,
            'discount' => 0,
        ],
        [
            'product_code' => 'ABC-124-X',
            'name' => 'Lorem Product 2',
            'qty' => 10,
            'unit_price' => 520,
            'discount' => 100,
        ],
        [
            'product_code' => 'ABC-125-X',
            'name' => 'Lorem Product 3',
            'qty' => 8,
            'unit_price' => 720,
            'discount' => 0,
        ],
        [
            'product_code' => 'ABC-126-X',
            'name' => 'Lorem Product 4',
            'qty' => 12,
            'unit_price' => 420,
            'discount' => 200,
        ],
        [
            'product_code' => 'ABC-127-X',
            'name' => 'Lorem Product 5',
            'qty' => 7,
            'unit_price' => 920,
            'discount' => 0,
        ],
    ],
    'products' => [
        [
            'id' => 1,
            'name' => 'Bag',
            'regular_price' => 800,
            'offer_price' => null,
            'category_name' => 'Fashion Accessories',
            'image' => '/img/products/bag.webp',
        ],
        [
            'id' => 2,
            'name' => 'Camera',
            'regular_price' => 1500,
            'offer_price' => 1200,
            'category_name' => 'Electronics',
            'image' => '/img/products/camera.webp',
        ],
        [
            'id' => 3,
            'name' => 'Helmet',
            'regular_price' => 500,
            'offer_price' => null,
            'category_name' => 'Outdoor Gear',
            'image' => '/img/products/helmet.jpg',
        ],
        [
            'id' => 4,
            'name' => 'Headphone',
            'regular_price' => 700,
            'offer_price' => 600,
            'category_name' => 'Electronics',
            'image' => '/img/products/headphone.webp',
        ],
        [
            'id' => 5,
            'name' => 'Joystick',
            'regular_price' => 400,
            'offer_price' => null,
            'category_name' => 'Gaming',
            'image' => '/img/products/joystick.webp',
        ],
        [
            'id' => 6,
            'name' => 'Watch',
            'regular_price' => 1200,
            'offer_price' => null,
            'category_name' => 'Fashion Accessories',
            'image' => '/img/products/watch.png',
        ],
        [
            'id' => 7,
            'name' => 'T-Shirt',
            'regular_price' => 40,
            'offer_price' => 30,
            'category_name' => 'Clothing',
            'image' => '/img/products/tshirt.webp',
        ],
        [
            'id' => 8,
            'name' => 'Jacket',
            'regular_price' => 1200,
            'offer_price' => null,
            'category_name' => 'Clothing',
            'image' => '/img/products/jacket.webp',
        ],
        [
            'id' => 9,
            'name' => 'iPhone 6',
            'regular_price' => 1500,
            'offer_price' => null,
            'category_name' => 'Electronics',
            'image' => '/img/products/ipone-6.jpg',
        ],
        [
            'id' => 10,
            'name' => 'Smart Watch',
            'regular_price' => 500,
            'offer_price' => null,
            'category_name' => 'Electronics',
            'image' => '/img/products/watch.webp',
        ],
    ],
];
